#!/bin/bash

# ==============================================================================
# Script 5: The Open Source Manifesto Generator
# Author: Yashraj Zaware (24BCE11157)
# Course: OSS Capstone Project - Unit 5 Final Task
# Description: An interactive tool that captures the user's personal FOSS 
# philosophy and exports it as a formatted manifesto file.
# ==============================================================================

# Custom alias-style note (Requirement for Unit 5)
# alias gen_manifesto='./script5_manifesto_generator.sh'

echo "============================================================"
echo "      WELCOME TO THE OSS PHILOSOPHY GENERATOR"
echo "============================================================"
echo "Please answer the following prompts to build your manifesto."
echo ""

# --- Interactive Input ---
# Capturing user input into variables for concatenation 
read -p ">> 1. Name an open-source tool you rely on daily: " USER_TOOL
read -p ">> 2. In one word, what does 'software freedom' mean to you? " USER_FREEDOM
read -p ">> 3. What is one thing you would build and share freely? " USER_BUILD

# Setting up metadata for the output file
GEN_DATE=$(date '+%d %B %Y')
CURRENT_USER=$(whoami)
OUTPUT_FILE="manifesto_${CURRENT_USER}.txt"

echo -e "\nProcessing your answers..."
sleep 1 # Adding a small pause for a 'human' processing feel

# --- File Generation (Writing to File) ---
# Using '>' to overwrite/create and '>>' to append [cite: 188, 200]
{
    echo "===================================================="
    echo "      PERSONAL OPEN SOURCE MANIFESTO"
    echo "===================================================="
    echo "Generated by : $CURRENT_USER (Audit: Yashraj Zaware)"
    echo "Date         : $GEN_DATE"
    echo "----------------------------------------------------"
    echo ""
    echo "In the digital age, tools like $USER_TOOL represent more"
    echo "than just code—they represent a collective effort to"
    echo "improve the world through transparency."
    echo ""
    echo "To me, the core of this movement is '$USER_FREEDOM'."
    echo "It is the right to see, change, and learn without"
    echo "proprietary barriers."
    echo ""
    echo "I commit to contributing back to this ecosystem. My"
    echo "goal is to build $USER_BUILD and release it under"
    echo "an open license for the benefit of the community."
    echo ""
    echo "----------------------------------------------------"
    echo "Software is a social contract. Let's keep it open."
    echo "===================================================="
} > "$OUTPUT_FILE"

# --- Output Confirmation ---
echo "Success! Your manifesto has been saved to: $OUTPUT_FILE"
echo "------------------------------------------------------------"
# Displaying the final result to the terminal [cite: 202]
cat "$OUTPUT_FILE"
echo "------------------------------------------------------------"
